ALTER TABLE portfolios DROP COLUMN user_id;
ALTER TABLE portfolios ADD COLUMN user_id UUID NOT NULL;
ALTER TABLE stocklists DROP COLUMN user_id;
ALTER TABLE stocklists ADD COLUMN user_id UUID NOT NULL;
ALTER TABLE transactions DROP COLUMN user_from;
ALTER TABLE transactions DROP COLUMN user_to;
ALTER TABLE transactions ADD COLUMN user_from UUID DEFAULT null;
ALTER TABLE transactions ADD COLUMN user_to UUID DEFAULT null;
ALTER TABLE users RENAME COLUMN id TO email;
ALTER TABLE users RENAME COLUMN passwd TO password_hash;
ALTER TABLE users ADD COLUMN id UUID DEFAULT uuid_generate_v4() NOT NULL;
ALTER TABLE users ADD COLUMN name TEXT NOT NULL;
ALTER TABLE users ADD COLUMN locked_at TIMESTAMP WITH TIME ZONE DEFAULT null;
ALTER TABLE users ADD COLUMN failed_login_attempts INT DEFAULT 0 NOT NULL;
