name: Haskell CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Haskell
      uses: haskell-actions/setup@v2
      with:
        ghc-version: '9.6.6'
        enable-stack: true
    - name: Cache stack
      uses: actions/cache@v3
      with:
        path: ~/.stack
        key: stack-${{ hashFiles('**/stack.yaml.lock') }}
        restore-keys: stack-
    - name: Cache cabal
      uses: actions/cache@v3
      with:
        path: ~/.cabal
        key: cabal-${{ hashFiles('**/*.cabal') }}
        restore-keys: cabal-

    - name: Build
      run: stack build